# Generated by Django 2.1.5 on 2019-01-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('nome_mae', models.CharField(max_length=50, verbose_name='Nome da Mae')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('grupo_amigo', models.CharField(choices=[('', (('PRÉDIO', 'Prédio'), ('ESCOLA', 'Escola')))], default='', max_length=10, verbose_name='Grupo de Amigo')),
            ],
            options={
                'verbose_name': 'Amigo',
                'verbose_name_plural': 'Amigos',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('etiqueta', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data de Emprestimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('amigo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Amigo')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicao', models.IntegerField(verbose_name='Numero da Edição')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Revista',
                'verbose_name_plural': 'Revistas',
            },
        ),
        migrations.AddField(
            model_name='colecao',
            name='tipo_edicao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='caixa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
    ]
